# -*- coding: utf-8 -*-
"""WRITING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxfywQAaoNl8mGOIfafyWD8i36cV1Wax
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/ASAP2_train_sourcetexts.csv', engine='python', on_bad_lines='skip')

df

df.info()

df.duplicated()

"""## Data Preprocessing

I will now preprocess the `full_text` column by performing the following steps:

1.  **Remove special characters:** Keep only alphanumeric characters and spaces.
2.  **Convert text to lowercase:** Standardize text for consistent processing.
3.  **Remove extra spaces:** Clean up multiple spaces and leading/trailing spaces.
4.  **Tokenization:** Break down text into individual words (tokens).
5.  **Stop-word removal (optional):** Remove common words that usually don't carry significant meaning.
"""

# Commented out IPython magic to ensure Python compatibility.
# Install NLTK if not already installed
# %pip install nltk

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# Re-execute cell 5db2eefe
import re

def clean_text(text):
    # Remove special characters (keep alphanumeric and spaces)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['cleaned_full_text'] = df['full_text'].apply(clean_text)

# Re-execute cell 7e200275
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

def tokenize_and_remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

df['processed_text'] = df['cleaned_full_text'].apply(tokenize_and_remove_stopwords)

display(df[['full_text', 'cleaned_full_text', 'processed_text']].head())

"""## Step 5: Feature Extraction

Now, let's extract some relevant features from the preprocessed text that can be used for traditional machine learning models. These features will help quantify different aspects of the essays.

### Word Count

Calculate the total number of words in the `processed_text` column (after tokenization and stop-word removal).
"""

df['word_count'] = df['processed_text'].apply(len)
display(df[['full_text', 'processed_text', 'word_count']].head())

"""### Sentence Count and Average Sentence Length

Calculate the number of sentences and the average number of words per sentence. This will be done on the `cleaned_full_text` to preserve sentence structure.
"""

from nltk.tokenize import sent_tokenize

def get_sentence_and_avg_word_length(text):
    sentences = sent_tokenize(text)
    sentence_count = len(sentences)

    total_words = 0
    for sent in sentences:
        total_words += len(word_tokenize(sent)) # Using word_tokenize on each sentence

    avg_sentence_length = total_words / sentence_count if sentence_count > 0 else 0
    return sentence_count, avg_sentence_length

df[['sentence_count', 'avg_sentence_length']] = df['cleaned_full_text'].apply(lambda x: pd.Series(get_sentence_and_avg_word_length(x)))
display(df[['full_text', 'sentence_count', 'avg_sentence_length']].head())

"""### Readability Score

Using the `textstat` library to calculate a readability score (e.g., Flesch-Kincaid Grade Level). First, we need to install the library.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install textstat

import textstat

def calculate_flesch_reading_ease(text):
    return textstat.flesch_reading_ease(text)

df['flesch_reading_ease'] = df['full_text'].apply(calculate_flesch_reading_ease)
display(df[['full_text', 'flesch_reading_ease']].head())

"""### Vocabulary Diversity

Calculate the lexical diversity using the ratio of unique words to total words in the `processed_text`.
"""

def calculate_vocabulary_diversity(tokens):
    if len(tokens) == 0:
        return 0
    return len(set(tokens)) / len(tokens)

df['vocabulary_diversity'] = df['processed_text'].apply(calculate_vocabulary_diversity)
display(df[['full_text', 'processed_text', 'vocabulary_diversity']].head())

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df[['word_count', 'sentence_count', 'avg_sentence_length', 'flesch_reading_ease', 'vocabulary_diversity']]
y = df['score']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""## Step 7: Train Traditional ML Models

Now, we'll train the specified traditional machine learning models using the preprocessed data and extracted features.

### 1. Random Forest Regressor
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Initialize and train the Random Forest Regressor
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions on the test set
rf_predictions = rf_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, rf_predictions)
r2_rf = r2_score(y_test, rf_predictions)

print(f"Random Forest - Mean Absolute Error: {mae_rf:.4f}")
print(f"Random Forest - R-squared: {r2_rf:.4f}")

"""### 2. XGBoost Regressor"""

# Commented out IPython magic to ensure Python compatibility.
# Install xgboost if not already installed
# %pip install xgboost

import xgboost as xgb

# Initialize and train the XGBoost Regressor
xgb_model = xgb.XGBRegressor(random_state=42)
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
xgb_predictions = xgb_model.predict(X_test)

# Evaluate the model
mae_xgb = mean_absolute_error(y_test, xgb_predictions)
r2_xgb = r2_score(y_test, xgb_predictions)

print(f"XGBoost - Mean Absolute Error: {mae_xgb:.4f}")
print(f"XGBoost - R-squared: {r2_xgb:.4f}")

"""### 3. Gradient Boosting Regressor"""

from sklearn.ensemble import GradientBoostingRegressor

# Initialize and train the Gradient Boosting Regressor
gbr_model = GradientBoostingRegressor(random_state=42)
gbr_model.fit(X_train, y_train)

# Make predictions on the test set
gbr_predictions = gbr_model.predict(X_test)

# Evaluate the model
mae_gbr = mean_absolute_error(y_test, gbr_predictions)
r2_gbr = r2_score(y_test, gbr_predictions)

print(f"Gradient Boosting - Mean Absolute Error: {mae_gbr:.4f}")
print(f"Gradient Boosting - R-squared: {r2_gbr:.4f}")

"""## Step 8: Evaluate Models

Let's gather all the evaluation metrics (MAE, RMSE, R²) for each model and present them in a clear summary to facilitate comparison.
"""

from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate RMSE for each model
rmse_rf = np.sqrt(mean_squared_error(y_test, rf_predictions))
rmse_xgb = np.sqrt(mean_squared_error(y_test, xgb_predictions))
rmse_gbr = np.sqrt(mean_squared_error(y_test, gbr_predictions))

# Display a consolidated summary of model performance
print("\n--- Model Performance Summary ---")
print("\nRandom Forest Regressor:")
print(f"  Mean Absolute Error (MAE): {mae_rf:.4f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_rf:.4f}")
print(f"  R-squared (R2): {r2_rf:.4f}")

print("\nXGBoost Regressor:")
print(f"  Mean Absolute Error (MAE): {mae_xgb:.4f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_xgb:.4f}")
print(f"  R-squared (R2): {r2_xgb:.4f}")

print("\nGradient Boosting Regressor:")
print(f"  Mean Absolute Error (MAE): {mae_gbr:.4f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_gbr:.4f}")
print(f"  R-squared (R2): {r2_gbr:.4f}")

"""### Clean Text Function

This function will handle removing special characters, converting text to lowercase, and eliminating extra spaces.
"""

import re

def clean_text(text):
    # Remove special characters (keep alphanumeric and spaces)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['cleaned_full_text'] = df['full_text'].apply(clean_text)
display(df[['full_text', 'cleaned_full_text']].head())

"""### Tokenization and Stop-word Removal

Next, the cleaned text will be tokenized (split into words), and common stop words will be removed to focus on more meaningful terms.
"""

import nltk
nltk.download('punkt_tab', quiet=True)
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

def tokenize_and_remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

df['processed_text'] = df['cleaned_full_text'].apply(tokenize_and_remove_stopwords)
display(df[['full_text', 'cleaned_full_text', 'processed_text']].head())

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, gbr_predictions)
print(mae)

"""## Step 9: Hyperparameter Tuning

Hyperparameter tuning is the process of finding the optimal set of hyperparameters for a machine learning model that results in the best performance on a given task. We will use `GridSearchCV` to systematically search through a predefined set of hyperparameter values for our best-performing model, the Gradient Boosting Regressor.
"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor

# Define the parameter grid for Gradient Boosting Regressor
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 4, 5],
    'min_samples_split': [2, 3],
    'min_samples_leaf': [1, 2]
}

# Initialize a fresh Gradient Boosting Regressor
gbr = GradientBoostingRegressor(random_state=42)

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=gbr, param_grid=param_grid,
                           cv=3, n_jobs=-1, verbose=2, scoring='neg_mean_absolute_error')

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

"""### Best Hyperparameters Found"""

print(f"Best parameters: {grid_search.best_params_}")
print(f"Best MAE score: {-grid_search.best_score_:.4f}")

"""### Evaluate Tuned Gradient Boosting Regressor"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Get the best model from GridSearchCV
best_gbr_model = grid_search.best_estimator_

# Make predictions on the test set with the best model
best_gbr_predictions = best_gbr_model.predict(X_test)

# Evaluate the best model
mae_best_gbr = mean_absolute_error(y_test, best_gbr_predictions)
rmse_best_gbr = np.sqrt(mean_squared_error(y_test, best_gbr_predictions))
r2_best_gbr = r2_score(y_test, best_gbr_predictions)

print("--- Tuned Gradient Boosting Regressor Performance ---")
print(f"  Mean Absolute Error (MAE): {mae_best_gbr:.4f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_best_gbr:.4f}")
print(f"  R-squared (R2): {r2_best_gbr:.4f}")

print("\n--- Comparison with Original Gradient Boosting Regressor ---")
print(f"Original MAE: {mae_gbr:.4f}, Tuned MAE: {mae_best_gbr:.4f}")
print(f"Original RMSE: {rmse_gbr:.4f}, Tuned RMSE: {rmse_best_gbr:.4f}")
print(f"Original R2: {r2_gbr:.4f}, Tuned R2: {r2_best_gbr:.4f}")

"""## Step 10: Save the Best Model

We will save the best-performing model, the original Gradient Boosting Regressor, to a `.pkl` file using `joblib`. This allows us to easily load and use the model for future predictions or deployment without retraining.
"""

import joblib

# Save the original Gradient Boosting Regressor model
model_filename = 'gbr_model.pkl'
joblib.dump(gbr_model, model_filename)

print(f"Best model saved to {model_filename}")

"""## Step 11: Create a Streamlit Application

Now, let's create a simple Streamlit application (`app.py`) that can load the saved model and take user input to make predictions. This script will demonstrate how to integrate your trained model into a web interface.

To run this Streamlit app:
1.  **Download the `gbr_model.pkl` file and the `app.py` file** (instructions below).
2.  Make sure you have Streamlit, scikit-learn, and joblib installed in your environment:
    `pip install streamlit scikit-learn joblib`
3.  Navigate to the directory where you saved `app.py` and `gbr_model.pkl` in your terminal.
4.  Run the command: `streamlit run app.py`

This will launch the Streamlit application in your web browser.
"""

streamlit_app_code = '''
import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Load the trained model
try:
    gbr_model = joblib.load('gbr_model.pkl')
    st.success("Model loaded successfully!")
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop() # Stop the app if the model can't be loaded

st.title('Essay Score Prediction App')
st.write('Enter the features below to predict the essay score.')

# Input fields for features
word_count = st.number_input('Word Count', min_value=0, value=100)
sentence_count = st.number_input('Sentence Count', min_value=1, value=5)
avg_sentence_length = st.number_input('Average Sentence Length', min_value=0.0, value=20.0)
flesch_reading_ease = st.number_input('Flesch Reading Ease', min_value=0.0, value=60.0)
vocabulary_diversity = st.number_input('Vocabulary Diversity (0.0 to 1.0)', min_value=0.0, max_value=1.0, value=0.75)

# Create a DataFrame for prediction
input_data = pd.DataFrame([[word_count, sentence_count, avg_sentence_length, flesch_reading_ease, vocabulary_diversity]],
                           columns=['word_count', 'sentence_count', 'avg_sentence_length', 'flesch_reading_ease', 'vocabulary_diversity'])

if st.button('Predict Score'):
    prediction = gbr_model.predict(input_data)[0]
    st.success(f'Predicted Essay Score: {prediction:.2f}')
'''

# Save the Streamlit app code to a file
with open('app.py', 'w') as f:
    f.write(streamlit_app_code)

print("Streamlit app script 'app.py' created.")

from google.colab import files

files.download('gbr_model.pkl')
files.download('app.py')

"""## Generate `requirements.txt`

To ensure reproducibility of the environment and for easy deployment (e.g., on Streamlit Cloud), it's good practice to provide a `requirements.txt` file. This file lists all the Python packages and their versions that your project depends on.
"""

import sys
import subprocess

def get_package_version(package_name):
    try:
        # Try to get version from pip list
        result = subprocess.run([sys.executable, '-m', 'pip', 'show', package_name], capture_output=True, text=True)
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                if line.startswith('Version:'):
                    return line.split(' ')[1]
        # Fallback to importing and checking __version__
        module = __import__(package_name.replace('-', '_')) # Handle packages with hyphens like scikit-learn
        return getattr(module, '__version__', None)
    except Exception:
        return None

required_packages = [
    'pandas',
    'numpy',
    'nltk',
    'scikit-learn',
    'xgboost',
    'joblib',
    'textstat',
    'streamlit'
]

requirements_content = []
for pkg in required_packages:
    version = get_package_version(pkg)
    if version:
        requirements_content.append(f"{pkg}=={version}")
    else:
        requirements_content.append(pkg) # Add without version if not found

requirements_str = '\n'.join(requirements_content)

with open('requirements.txt', 'w') as f:
    f.write(requirements_str)

print("Generated requirements.txt:")
print(requirements_str)

# Optional: Download the file
from google.colab import files
files.download('requirements.txt')